# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ROOT: Resonite~/ResoniteHook

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: cd "$ROOT"; dotnet restore
    - name: Build
      run: cd "$ROOT"; dotnet build --no-restore
    - name: Test
      run: cd "$ROOT"; dotnet test --no-build --verbosity normal
