# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ROOT: Resonite~/ResoniteHook

jobs:
  build:

    runs-on: windows-latest

    steps:

    - name: Setup steamcmd
      run: |
        cd c:\
        Invoke-WebRequest https://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip -OutFile c:\steamcmd.zip
        Expand-Archive c:\steamcmd.zip -Force
        New-Item -ItemType Directory -Path "C:\Program Files (x86)\Steam\steamapps\common\Resonite\Resonite_Data\Managed"
        dir c:\steamcmd

    - name: Update steamcmd
      run: |
        $ErrorAction = "Ignore"
        # run updater first
        c:\steamcmd\steamcmd +quit
        # steamcmd exits with a nonzero error code even when successful, suppress the error
        Exit 0

    - name: Install resonite
      run: |
        c:\steamcmd\steamcmd +force_install_dir "C:\Program Files (x86)\Steam\steamapps\common\Resonite\Resonite_Data\Managed" +login ${{ secrets.STEAMUSER }} ${{ secrets.STEAMPASS }} +app_update 2519830 +quit
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x 
    - uses: actions/checkout@v4

    - name: Restore dependencies
      run: cd "$ROOT"; dotnet restore
    - name: Build
      run: cd "$ROOT"; dotnet build --no-restore
    - name: Test
      run: cd "$ROOT"; dotnet test --no-build --verbosity normal
