name: Update resonite cache

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: '37 4 * * *' # every day at 4:37 UTC
    
    
env:
  RPC_SERVER_SRC: Resonite~/ResoniteHook
  RESONITE_PATH: "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Resonite"
  CACHE_SALT: -v2
  

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Cache resonite
        id: cache-resonite
        uses: actions/cache@v4
        with:
          path: "${{ env.RESONITE_PATH }}"
          key: resonite-${{ env.CACHE_SALT }}

      - name: Cache steamcmd
        id: cache-steamcmd
        uses: actions/cache@v4
        with:
          path: c:\steamcmd
          key: steamcmd

      - name: Setup steamcmd
        if: steps.cache-steamcmd.outputs.cache-hit != 'true'
        run: |
          cd c:\
          Invoke-WebRequest https://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip -OutFile c:\steamcmd.zip
          Expand-Archive c:\steamcmd.zip -Force
          New-Item -ItemType Directory -Path "${{ env.RESONITE_PATH }}" -Force
          dir c:\steamcmd

      - name: Update steamcmd
        run: |
          $ErrorAction = "Ignore"
          # run updater first
          c:\steamcmd\steamcmd +quit
          # steamcmd exits with a nonzero error code even when successful, suppress the error
          Exit 0


      - name: Install or update resonite
        id: install-resonite
        run: |
          c:\steamcmd\steamcmd +force_install_dir "${{ env.RESONITE_PATH }}" +login ${{ secrets.STEAMUSER }} ${{ secrets.STEAMPASS }} +app_update 2519830 +quit